defmodule Tako.Repo.Migrations.AddTimestampsToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :stamps_collected, :bigint, default: 0
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      modify :stamps_collected, :bigint, default: nil
    end
  end
end